version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bolt_postgres
    environment:
      POSTGRES_DB: ralie
      POSTGRES_USER: bolt_user
      POSTGRES_PASSWORD: bolt_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bolt_network

volumes:
  postgres_data:

networks:
  bolt_network:
    driver: bridge
